export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          role: string
          created_at?: string
          updated_at?: string
          full_name?: string
          phone?: string
          avatar_url?: string
        }
        Insert: {
          id?: string
          email: string
          role: string
          created_at?: string
          updated_at?: string
          full_name?: string
          phone?: string
          avatar_url?: string
        }
        Update: {
          id?: string
          email?: string
          role?: string
          created_at?: string
          updated_at?: string
          full_name?: string
          phone?: string
          avatar_url?: string
        }
      }
      shops: {
        Row: {
          id: string
          name: string
          owner_id: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          phone?: string
          email?: string
          website?: string
          logo_url?: string
          created_at?: string
          updated_at?: string
          status: string
        }
        Insert: {
          id?: string
          name: string
          owner_id: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          phone?: string
          email?: string
          website?: string
          logo_url?: string
          created_at?: string
          updated_at?: string
          status: string
        }
        Update: {
          id?: string
          name?: string
          owner_id?: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          phone?: string
          email?: string
          website?: string
          logo_url?: string
          created_at?: string
          updated_at?: string
          status?: string
        }
      }
      branches: {
        Row: {
          id: string
          shop_id: string
          name: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          latitude?: number
          longitude?: number
          phone?: string
          email?: string
          manager_id?: string
          created_at?: string
          updated_at?: string
          status: string
        }
        Insert: {
          id?: string
          shop_id: string
          name: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          latitude?: number
          longitude?: number
          phone?: string
          email?: string
          manager_id?: string
          created_at?: string
          updated_at?: string
          status: string
        }
        Update: {
          id?: string
          shop_id?: string
          name?: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          latitude?: number
          longitude?: number
          phone?: string
          email?: string
          manager_id?: string
          created_at?: string
          updated_at?: string
          status?: string
        }
      }
      scooters: {
        Row: {
          id: string
          shop_id: string
          name: string
          model: string
          description?: string
          year?: number
          license_plate?: string
          status: string
          hourly_rate: number
          daily_rate: number
          weekly_rate: number
          image_urls?: string[]
          fuel_type?: string
          fuel_level?: number
          battery_level?: number
          mileage?: number
          color?: string
          engine_size?: number
          last_maintenance?: string
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id?: string
          shop_id: string
          name: string
          model: string
          description?: string
          year?: number
          license_plate?: string
          status: string
          hourly_rate: number
          daily_rate: number
          weekly_rate: number
          image_urls?: string[]
          fuel_type?: string
          fuel_level?: number
          battery_level?: number
          mileage?: number
          color?: string
          engine_size?: number
          last_maintenance?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          shop_id?: string
          name?: string
          model?: string
          description?: string
          year?: number
          license_plate?: string
          status?: string
          hourly_rate?: number
          daily_rate?: number
          weekly_rate?: number
          image_urls?: string[]
          fuel_type?: string
          fuel_level?: number
          battery_level?: number
          mileage?: number
          color?: string
          engine_size?: number
          last_maintenance?: string
          created_at?: string
          updated_at?: string
        }
      }
      bookings: {
        Row: {
          id: string
          rider_id: string
          scooter_id: string
          shop_id: string
          start_time: string
          end_time: string
          total_amount: number
          status: string
          payment_status: string
          created_at?: string
          updated_at?: string
          pickup_code?: string
          return_code?: string
          actual_return_time?: string
          notes?: string
        }
        Insert: {
          id?: string
          rider_id: string
          scooter_id: string
          shop_id: string
          start_time: string
          end_time: string
          total_amount: number
          status: string
          payment_status: string
          created_at?: string
          updated_at?: string
          pickup_code?: string
          return_code?: string
          actual_return_time?: string
          notes?: string
        }
        Update: {
          id?: string
          rider_id?: string
          scooter_id?: string
          shop_id?: string
          start_time?: string
          end_time?: string
          total_amount?: number
          status?: string
          payment_status?: string
          created_at?: string
          updated_at?: string
          pickup_code?: string
          return_code?: string
          actual_return_time?: string
          notes?: string
        }
      }
      rider_profiles: {
        Row: {
          id: string
          user_id: string
          license_number: string
          license_country: string
          license_expiry: string
          date_of_birth?: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          emergency_contact_name?: string
          emergency_contact_phone?: string
          created_at?: string
          updated_at?: string
          verification_status: string
          license_image_url?: string
          id_image_url?: string
          selfie_url?: string
        }
        Insert: {
          id?: string
          user_id: string
          license_number: string
          license_country: string
          license_expiry: string
          date_of_birth?: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          emergency_contact_name?: string
          emergency_contact_phone?: string
          created_at?: string
          updated_at?: string
          verification_status: string
          license_image_url?: string
          id_image_url?: string
          selfie_url?: string
        }
        Update: {
          id?: string
          user_id?: string
          license_number?: string
          license_country?: string
          license_expiry?: string
          date_of_birth?: string
          address?: string
          city?: string
          country?: string
          postal_code?: string
          emergency_contact_name?: string
          emergency_contact_phone?: string
          created_at?: string
          updated_at?: string
          verification_status?: string
          license_image_url?: string
          id_image_url?: string
          selfie_url?: string
        }
      }
      // Add other tables as needed
    }
  }
}
